### ISSUE TITLE
Informationen Vogelart

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#10]
Es wäre praktisch, wenn es möglich wäre bei einem Patienten auf des Art zu klicken und dann ein Kurzprofil über diese Art zu erhalten. Bei der Kurzbeschreibung sollte dann zu sehen sein was dieser Vogel frisst. Somit hätten unerfahrene Hilfskräfte eine Möglichkeit schnell zu sehen welche Nahrungsmittel sie zu den Auswilderungsvolieren mitbringen müssen.

**Comment by guntherweissenbaeck** [comment]
Krichmerhinn

**Comment by guntherweissenbaeck** [comment]
Soll es da im admin-Bereich einen wysiwyg-Editor geben?

**Comment by Java-Fish** [comment]
Erst mal nicht, außer du hast Spaß dran. Im Adminbereich bin erst mal nur ich aktiv 

Für Version 1.x dann gern. :) außer du hast Spaß dran

**Comment by guntherweissenbaeck** [comment]
Hilfeseite wurde eingerichtet
