### ISSUE TITLE
Zustand Volieren

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#16]
Folgende Zustände dürfen Volieren haben:
- Offen
- Geschlossen
- Gesperrt

Offen und Geschlossen bezieht sich hierbei auf die Volierentür und Defekt bedeutet, dass in diese Voliere keine Vögel dürfen, da die Voliere nicht sicher ist.

**Comment by guntherweissenbaeck** [comment]
Im Grunde erledigt, Sollte aber der Benutzer den Zustand der Voliere ändern können, oder obliegt das einzig dem Admin?

**Comment by Java-Fish** [comment]
Den Zustand der Voliere muss jeder ändern können. Sobald ein Vogel in einem guten Zustand ist, muss die Person die Vollieren öffnen und den Vogel freilassen. Damit am nächsten Tag niemand geschockt ist, dass die Volieren offen ist und der Vogel weg, soll in der App dieser Status angezeigt werden.

**Comment by guntherweissenbaeck** [comment]
erledit
