### ISSUE TITLE
Nur Details von einem Patienten

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#19]
In der Patientenübersicht ist es in der mobilen Ansicht möglich, mit einem Klick auf das + mehr Details zum Patienten zu sehen. Wenn man auf das nächste + vom nächsten Patienten klickt, bleibt die Übersicht des alten Patienten offen. Hier wäre es schön, wenn die Übersicht des vorherigen Patienten eingeklappt wird.

**Comment by guntherweissenbaeck** [comment]
erledigt
