### ISSUE TITLE
CSV Export

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#2]
Damit die Daten später ausgewertet werden könne, muss ein CSV Export möglich sein. Wünschenswert wäre ein Export aller Vögel ohne Retter und ein Export mit Vögeln und deren Retter.

**Comment by guntherweissenbaeck** [comment]
Soll der Export nur im adminbereich möglich sein, oder auch für Benutzer?

**Comment by Java-Fish** [comment]
Es reicht im Adminbereich. Für die Nutzer im Alltag sollen die Funktionen so gering wie möglich sein. Was nicht vorhanden ist, kann nicht falsch genutzt werden.

**Comment by Java-Fish** [comment]
Export klappt super

**Comment by guntherweissenbaeck** [comment]
Überschriften des Exports anpassen und neu sortieren

**Comment by guntherweissenbaeck** [comment]
done
