### ISSUE TITLE
Neuer Status "Übermittelt"

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#22]
Ein Vogel kann vom Status "In Pflege" auch in den Status "Übermittelt" wechseln. Das bedeutet, dass der Vogel an eine andere Wildvogelhilfe übergeben wurde. Als Status reicht "Übermittelt", allerdings muss dann zusätzlich eine Abfrage mit Texteingabe kommen, in welcher die Station eingetippt wird, an die der Vogel übermittelt wurde.

**Comment by guntherweissenbaeck** [comment]
Done
