### ISSUE TITLE
Kosten Vogel nur im 1 Cent Bereich zu erhöhen

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#23]
Neben dem Feld Kosten in der Patientenübersicht muss es eine Schaltfläche mit einem + geben. Wenn darauf gedrückt wird, öffnet sich ein Pop-up und es kann ein Betrag eingegeben und bestätigt werden. Dieser Betrag wird dann auf den bestehenden Betrag des Patienten addiert.
Reduzieren des Betrags muss der Endnutzer nicht machen. Es reicht aus, wenn diese Funktion über den Admin-Bereich erledigt werden kann

**Comment by Java-Fish** [comment]
Bitte auch nicht den Nutzer rechnen lassen sondern anfragen wie viel hinzugefügt werden soll. Es besteht sonst die Gefahr, dass die Person statt der Summe nur die neuen Kosten einträgt und somit den alten Wert überschreibt.

**Comment by guntherweissenbaeck** [comment]
Kosten App fertig. Es fehlt in der Patienten-übersicht die Summe aller Ausgaben pro Patient! (Challenge!!!)
