### ISSUE TITLE
Kostenposten mit Datum

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#24]
Jedes mal, wenn Kosten auf einen Patienten addiert werden muss im Hintergrund die Summe und das Datum zu dieser Aktion gespeichert werden. In der Patientenübersicht reicht weiterhin die Gesamtsumme. Sobald die Funktion des Exports von Daten vorhanden ist, müssen bei einem Export eines einzelnen Vogels die Daten der Summen mit aufgelistet werden.

**Comment by guntherweissenbaeck** [comment]
Erledigt
