### ISSUE TITLE
Automatische Meldung an UNB

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#26]
Sobald bestimmte Vogelarten bei der WVH aufgenommen werden, muss sofort eine Meldung an die UNB erfolgen. Hier soll die App, sobald die Aufnahmedaten ausgefüllt wurde, eine E-Mail an die UNB Jena (umweltschutz@jena.de) versenden.
Absender: post@nabu-jena.de
Betreff der E-Mail: Meldepflichtiges Tier aufgenommen

Inhalt der E-Mail
- Art des Tieres
- Datum der Aufnahme
- Finder
- Fundort
- Erstbefund

Signatur:
Wildvogelhilfe Jena
NABU Kreisverband Jena e.V.
Schillergässchen 5
07745 Jena
---
Diese E-Mail wurde automatisch generiert.

**Comment by Java-Fish** [comment]
Eine Liste der meldepflichtigen Arten ist unter folgendem Link zu finden:

https://www.wisia.de/GetNames?check_search_partname=on&lang=deu&taxon=&workgroup_id=2&check_rw=1266&check_viewimg=1&Suchen=Suche

Jedes Tier welches in der Spalte BG mit einem s markiert ist ist streng geschützt. Eine Liste dieser spezifischen Arten stelle ich zur Verfügung

**Comment by Java-Fish** [comment]
Drosselrohrsänger
Seggenrohrsänger
Schilfrohrsänger
Flussuferläufer
Eisvogel
Steinhuhn
Rothuhn
Brachpieper
Purpurreiher
Steinwälzer
Moorente
Rohrdommel
Triel
Alpenstrandläufer
Ziegenmelker
Karmingimpel
Seeregenpfeifer
Flussregenpfeifer
Sandregenpfeifer
Weißflügelseeschwalbe
Trauerseeschwalbe
Weißstorch
Blauracke
Wachtelkönig
Singschwan
Weißrückenspecht
Mittelspecht
Schwarzspecht
Grauammer
Zippammer
Zaunammer
Ortolan
Mornellregenpfeifer
Halsbandschnäpper
Zwergschnäpper
Papageitaucher
Eissturmvogel
Haubenlerche
Bekassine
Doppelschnepfe
Teichhuhn
Eistaucher
Lachseeschwalbe
Stelzenläufer
Sturmschwalbe
Zwergdommel
Wendehals
Nördlicher Raubwürger
Schwarzstirnwürger
Rotkopfwürger
Uferschnepfe
Rohrschwirl
Heidelerche
Blaukehlchen
Zwergschnepfe
Bienenfresser
Steinrötel
Großer Brachvogel
Nachtreiher
Wellenläufer
Steinsperling
Odinshühnchen
Kampfläufer
Berglaubsänger
Dreizehenspecht
Grauspecht
Grünspecht
Braunsichler
Goldregenpfeifer
Ohrentaucher
Rothalstaucher
Schwarzhalstaucher
Kleines Sumpfhuhn
Tüpfelsumpfhuhn
Zwergsumpfhuhn
Felsenschwalbe
Säbelschnäbler
Uferschwalbe
Zitronengirlitz
Zwergseeschwalbe
Raubseeschwalbe
Rosenseeschwalbe
Fluss-Seeschwalbe
Küstenseeschwalbe
Brandseeschwalbe
Sperbergrasmücke
Birkhuhn
Auerhuhn
Bruchwasserläufer
Waldwasserläufer
Teichwasserläufer
Rotschenkel
Wiedehopf
Kiebitz

**Comment by Java-Fish** [comment]
Alle die oben aufgelisteten Arten sind in nach BNatSchG streng geschützte Arten und müssen per Mail gemeldet werden.

**Comment by Java-Fish** [comment]
Für die größt mögliche Flexibilität bitte die Umsetzung wie folgt gestalten:

- Im Adminportal pro Art ein Textfeld für E-Mail-Adressen einrichten
- E-Mail-Adressen sind kommasepariert
- sobald ein neuer Patient angelegt wurde erhalten alle hinterlegten Empfänger zu dieser Art eine Infomail

Design der Mail:

**Betreff:**
Geschützte Art in der Wildvogelhilfe Jena aufgenommen

**Inhalt:**
- Art
- Aufnahmedatum
- Fundort
- Erstdiagnosen
- Finder (alle Kontaktdaten)

Bei Fragen wenden Sie sich bitte direkt an die Wildvogelhilfe Jena via E-Mail: wildvogelhilfe@nabu-jena.de

Diese E-Mail wurde automatisch generiert.

**Comment by Java-Fish** [comment]
Reduzierung für ersten Entwurf:

- Eigener Bereich im Adminbereich
- In diesem Bereich gibt es eine Auflistung aller Arten, die in der App angelegt sind
- Vor jeder Art gibt es eine Checkbox
- Zusätzlich gibt es in diesem Bereich ein Textfeld mit kommaseparierten E-Mail-Adressen

Wann immer ein neuer Patient angelegt wird, dessen Art einen Haken im Backend gesetzt hat, dann wird nach dem Anlegen automatisch eine E-Mail an die hinterlegten E-Mail-Adressen gesendet.

Die E-Mail hat ein festes Template nach dem folgenden Muster:

Betreff: Neuer Wildvogel aufgenommen

Inhalt:

Guten Tag,

am <DATUM> wurde in der NABU Wildvogelhilfe ein Vogel der Art <ART> aufgenomen.
Der Fundort laut Finder*in war: <FUNDORT>
Die Diagnose bei Fund lautet: <DIAGNOSE BEI FUND>

Mit freundlichen Grüßen

NABU Wildvogelhilfe Jena
Untergliederung des
NABU Kreisverband Jena e.V.
Schillergässchen 5
07745 Jena

**Comment by guntherweissenbaeck** [comment]
Bitte in der Produktivumgebung die Credentials aktualisieren. Das Rücksetzen des Passworts funktioniert nicht.
