### ISSUE TITLE
Nutzerregistrierung

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#27]
Wie können wir neue Nutzer registrieren?
Wunsch:
Admin kann an einer Stelle E-Mail Adresse angeben und an diese wird eine Einladungsmail versendet. Nutzer gibt dann selber Nutzername und Passwort ein.

KEINE SELBSTREGESTRIERUNG, NUR MIT EINLADUNG.

Für 1.0:
Admin legt Nutzer mit Nutzername, E-Mail und Passwort im Adminbereich händisch an

**Comment by guntherweissenbaeck** [comment]
https://www.youtube.com/watch?v=qqFCt0Yde40

**Comment by guntherweissenbaeck** [comment]
für die Nutzregistrierung und Passwortrücksetzung wäre es gut, einen separaten Email-Account (fbf@nabu-jena.de) zur Verfügung zu stellen.

**Comment by guntherweissenbaeck** [comment]
1. Nutzer im Admin bereich erstellen
2. Email aDresse hinzufügen
3. Abmelden und im Login Bereich für die soeben angelgte Email-Adresse das Passwort zurücksetzen
4. Benutzer bekommt dann eine Email von der im .env-File hinterlegten Email-Adresse
