### ISSUE TITLE
Patient schreibgeschützt

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#29]
Sobald der Status auf verstorben, ausgewildert oder übermittelt gestellt und gespeichert wurde muss der Vogel aus der Übersicht der Patienten verschwinden und schreibgeschützt werden.

**Comment by guntherweissenbaeck** [comment]
Soll es dafür eine weitere Übersicht "ehemalige Patienten" geben?

**Comment by Java-Fish** [comment]
Jupp das wäre super

**Comment by guntherweissenbaeck** [comment]
erledigt. Link auf Seite aller Patienten

**Comment by guntherweissenbaeck** [comment]
Filter funktioniert noch nicht

**Comment by guntherweissenbaeck** [comment]
Filter funktioniert
