### ISSUE TITLE
Kostenerfassung

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#3]
Für jeden Vogel muss es die Möglichkeit der Kostenerfassung geben. Hierbei muss nicht der Verlauf der Kosten, aber die Gesamtsumme in der Datenbank stehen. Jedes Mal, wenn neue Kosten entstanden sind, müssen diese durch eine +-Schaltfläche zu den bereits bestehenden Kosten addiert werden.

**Comment by guntherweissenbaeck** [comment]
Muss es auch die Möglichkeit geben, die Kosten auch zu verringern (siehe Falschbuchung)

**Comment by Java-Fish** [comment]
Vermutlich ja. Also ein Label mit den aktuellen Kosten und daneben die + und - Schaltflächen

**Comment by guntherweissenbaeck** [comment]
Kostenerfassung kann editiert werden
