### ISSUE TITLE
Archiv

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#30]
Neue View mit einer Übersicht über alle Vögel die verstorben, ausgewildert oder vermittelt wurden. Auflistung der Vögel wie in der Patientensicht mit dem Plus zum aufklappen, allerdings darf nichts mehr bearbeitet werden.
Suchfunktion über alle Werte wäre praktisch.

**Comment by guntherweissenbaeck** [comment]
Erledigt
