### ISSUE TITLE
Alter des Patienten

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#31]
Für den Patienten benötigen wir dessen Alter bei der Aufnahme. Das Alter soll nur bei der Aufnahme abgefragt und danach nicht mehr änderbar sein.
Beispielfeldname: Alter bei Aufnahme
Optionen:
- Ei
- Nestling
- Ästling
- Adult

**Comment by guntherweissenbaeck** [comment]
erledigt
