### ISSUE TITLE
Geschlecht Patient

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#32]
Bitte bei der Aufnahme des Patienten das Geschlecht mit abfragen.
Optionen:
- Weiblich
- Männlich
- Unbekannt

Das Geschlecht muss später auch bearbeitet werden können, da es häufig zu Beginn falsch bestimmt wir oder schlichtweg nicht bestimmbar ist.

**Comment by guntherweissenbaeck** [comment]
erledigt
