### ISSUE TITLE
Erklärtexte anpassen

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#35]
kwt

**Comment by guntherweissenbaeck** [comment]
kwt?

**Comment by Java-Fish** [comment]
kein weiterer Text :) Die Beschreibung sagt schon alles. Ich muss nur noch die Texte anpassen, dafür benötige ich allerdings noch Informationen.

**Comment by guntherweissenbaeck** [comment]
erledigt
