### ISSUE TITLE
Kennung der Patienten

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#4]
Jeder Vogel benötigt eine eindeutige Kennung, damit unterschieden werden kann, welches Individuum einer Art genau gemeint ist. Da eine UUID schlecht lesbar ist, wäre hier eine kurze Nummer wie in einem Ticketsystem praktisch.  Fünfstellig Hexadezimal sollte mehr als ausreichend sein und auch noch Lesebar

00000 - FFFFF

**Comment by guntherweissenbaeck** [comment]
Als Kennung wurde ein Patienten-Alias eingeführt. Dieser wird bei der Erstellung des Patienten automatisch generiert. Der Alias besteht aus einem Vornamen und einen Nachnamen. Die Namen können slebstverständlich bei Nichtgefallen geändert werden.
