### ISSUE TITLE
Status "In Auswilderung"

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#5]
Nachdem ein Vogel selbstständig fressen kann und keine schweren Verletzungen hat, kommt dieser in eine Auswilderungsvoliere. Hierfür muss es eine neue View in der Webapp geben, damit man sieht, ob in den Volieren Vögel sind und welche Vögel in den Volieren sind.
Die View sollte eine Liste der existierenden Volieren sein. Zu den Volieren muss angezeigt werden, ob diese derzeit offen oder geschlossen sind und welche Vögel derzeit in den Volieren sind. Zudem braucht jede Volieren einen Beschreibungstext, damit man diese auseinander halten kann.

**Comment by guntherweissenbaeck** [comment]
Es exisiteirt der Status der Auswilderung. Hierbei sollte im nächsten Schritt eine JavaScript-Logik erstellt werden, die das Auswahlfeld Voliere erscheinen oder verschwinden lässt, wenn der entsprechende Status des Patienten gewählt wird

**Comment by guntherweissenbaeck** [comment]
Erledigt
