### ISSUE TITLE
Description werden nicht gespeichert

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#50]
Descriptions von Vögeln werden in der Adminoberfläche nicht gespeichert

**Comment by guntherweissenbaeck** [comment]
Habe vorerst de WYSISWYG Editor entfernt, da er nicht funktioniert. Die Einträge im Adminbereich sind aber dennoch als HTML-Seite einzufügen. Sie werden dann im Frontend korrekt dargestellt.
