### ISSUE TITLE
Anonymer Finder

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#51]
Es kommt immer wieder vor, dass wir zu einem Vogel keinen Finder haben. In diesem Fall muss ein anonymer Finder angegeben werden. Diesen bitte beim Neuanlegen eines Patienten im Dropdownmenü der Finder an oberster Stelle anzeigen und dessen Text fett und orange machen.

**Comment by guntherweissenbaeck** [comment]
Done! Siehe issue#62
