### ISSUE TITLE
Finder: Nicht alle Daten erforderlich

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#52]
Bitte das Formular für Finder so abändern, dass nicht alle Informationen erforderlich sind. Vielmehr sollte geprüft werden, dass mindestens ein Feld ausgefüllt ist.

**Comment by guntherweissenbaeck** [comment]
Welche Felder können da "weg"

**Comment by Java-Fish** [comment]
Leider alle. Es kann sein das ein Finder dann nur noch aus einer Telefonnummer besteht, oder nur aus einer Straße mit Hausnummer, oder nur eine E-Mail, oder eine beliebige Kombination

**Comment by Java-Fish** [comment]
Nach Rücksprache mit der UNB ist folgendes Pflicht:
- Vorname
- Nachname
- Adresse

Eine Adresse kann hierbei die Anschrift mit mit
- Straße
- Hausnummer
- Stadt
oder eine Telefonnummer sein, beides sollte auch möglich sein

**Comment by guntherweissenbaeck** [comment]
Done! Siehe issue#62
