### ISSUE TITLE
Freitextfeld Patienten

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#53]
Sobald ein Patient angelegt wurde, soll in dessen Profil ein Freitextfeld vorhanden sein, in welches beliebige Informationen geschrieben werden können.

**Comment by guntherweissenbaeck** [comment]
Soll es möglich sein, auch sehr viel Text dort hineinzuschreiben. Es geht um dem Datentypen, den ich dem Feld zuweise: 256 Zeichen oder auch mehr?

**Comment by Java-Fish** [comment]
Lieber mehr. Im schlimmsten Fall kann es zu einer Anzeige kommen und in diesem Fall sollte dort zumindest das polizeiliche Aktenzeichen, das Aktenzeichen des Ordnungsamtes und Kontaktdaten von Behörden sowie der Verfahrensprozess aufgeschrieben werden können. Eventuell könnte man auch wie hier Kommentare an einen Patienten hängen. Jedes Kommentar wir dann an den Patienten als einzelner Text angehangen. Diese Kommentare können wir dann gern auf 255 Zeichen beschränken. Bearbeitbar müssen dann die Kommentare nicht sein, denn Korrekturen könnte man im Adminportal oder durch einen neuen Kommentare durchführen.

**Comment by Java-Fish** [comment]
Wenn ich darüber nachdenke, wäre eine Kommentarfunktion schon richtig geil, aber auch ein Super-Sternchen-Feature, muss also nicht.

**Comment by guntherweissenbaeck** [comment]
Done
