### ISSUE TITLE
Finder als eigene Abfrage entfernen

### ISSUE THREAD

**Issue by Java-Fish** [guntherweissenbaeck/django_fbf#62]
1. Beim Anlegen des Patienten soll nicht mehr direkt nach dem Finder gefragt werden. Stattdessen soll direkt das Formular für die Patienten angezeigt werden. 
2. Das Formular der Patienten soll um ein Feld für Finderinformationen erweitert werden.
3. Die bisherigen Daten müssen in der Datenbank migriert werden, sodass alle bisherigen Finder in das Freitextfeld der Patienten eingetragen werden.

**Comment by guntherweissenbaeck** [comment]
Sollen die bisher eingegeben Finder-Adress-Daten in das Patienten-Finder-Feld übernommen werden?

**Comment by Java-Fish** [comment]
Jupp

**Comment by guntherweissenbaeck** [comment]
https://github.com/guntherweissenbaeck/django_fbf/wiki/Add-Finder-to-Patient
